org: tranduc2702
app: backend-coding-test
service: backend-coding-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-offline
  #- '@hewmen/serverless-plugin-typescript'  
  #- serverless-plugin-optimize

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md
  individually: true
  excludeDevDependencies: true

functions:
  main:
    handler: dist/src/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any

# functions:
#   api:
#     handler: dist/src/index.handler
#     events:
#       - http:
#           path: /
#           method: ANY
#       - http:
#           path: /{proxy+}
#           method: ANY

# custom:
#   optimize:
#     external: ['swagger-ui-dist']