org: tranduc2702
app: backend-test-stayr
service: backend-test-stayr

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    DB_DIALECT: 'postgres'
    DB_NAME: 'mcmmwcrr'
    DB_USERNAME: 'mcmmwcrr'
    DB_PASSWORD: 'xRhg-KXjqVIa3sEaBaZRw3CEkjU24IF_'
    DB_HOST: 'fanny.db.elephantsql.com'
    DB_PORT: '5432'

plugins:
  - serverless-offline
  - serverless-sequelize-migrations

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md
  individually: true
  excludeDevDependencies: true

functions:
  main:
    handler: dist/src/index.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
  blogTitle: 
    handler: "dist/src/cron/index.handler"
    events:
    - schedule: rate(1 minute)